name: PHP

on: [push]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        ini-values: post_max_size=256M, max_execution_time=180

    - name: Validate Composer
      run: composer validate
    - name: Install Composer Deps
      run: composer install
    - name: Run Tests
      run: composer test
